ame: Deploy Database

on:
  push:
    branches:
      - main # Cambia esto según tu rama principal

jobs:
  deploy-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PostgreSQL
      uses: cortinico/setup-pg-wait@v1

    - name: Create and Populate Database
      run: |
        psql -U ${{ secrets.DB_USERNAME }} -d ${{ secrets.DB_NAME }} -h localhost -p 5432 -c "CREATE TABLE example (id serial primary key, name text);"
        psql -U ${{ secrets.DB_USERNAME }} -d ${{ secrets.DB_NAME }} -h localhost -p 5432 -c "INSERT INTO example (name) VALUES ('Example Data');"

    - name: Check Database
      run: |
        psql -U ${{ secrets.DB_USERNAME }} -d ${{ secrets.DB_NAME }} -h localhost -p 5432 -c "SELECT * FROM example;"
